### ISSUE TITLE
Symlinking between build and cloned directories with Ansible

### ISSUE THREAD

**Issue by joasilva** [CSCfi/qvain-ops#9]
cd /ansible/devs/qvain-ops/releases/production
ln -s ../../qvain-api/bin
ln -s ../../qvain-api/doc
ln -s ../../qvain-api/schema
ln -s ../../qvain-js/dist

Should be linked with:
$ ll
total 36
drwxr-xr-x.  5 4096 May  8 13:30 ansible
drwxr-xr-x.  2 4096 Mar 20 13:39 docs
drwxr-xr-x. 16  4096 Mar 20 14:01 qvain-api
drwxr-xr-x. 12 4096 Mar 20 15:52 qvain-js
-rw-r--r--.  1 1866 May  8 13:30 README.md
drwxr-xr-x.  2 4096 Mar 20 13:39 releases
drwxr-xr-x.  2 4096 Mar 20 13:39 rpm
drwxr-xr-x.  2  4096 Mar 20 13:39 scripts
-rw-r--r--.  1 1912 Mar 20 14:02 Vagrantfile

Desired end result:
cd /ansible/devs/qvain-ops/releases/production
ln -s ../../qvain-api/bin
ln -s ../../qvain-api/doc
ln -s ../../qvain-api/schema
ln -s ../../qvain-js/dist

[root@fairdeploy production]# pwd
/ansible/devs/qvain-ops/releases/production
[root@fairdeploy production]# ll
total 0
lrwxrwxrwx 1 ansiblefd ansiblefd 19 May  8 11:54 bin → ../../qvain-api/bin
lrwxrwxrwx 1 ansiblefd ansiblefd 19 May  8 11:54 dist → ../../qvain-js/dist
lrwxrwxrwx 1 ansiblefd ansiblefd 19 May  8 11:53 doc → ../../qvain-api/doc
lrwxrwxrwx 1 ansiblefd ansiblefd 22 May  8 11:53 schema → ../../qvain-api/schema

**Comment by tahme** [comment]
With the current nginx configuration, the link to qvain-js/dist should be named web, so 
`ln -s ../../qvain-js/dist web`
and
`dist → ../../qvain-js/dist`
becomes
`web → ../../qvain-js/dist`

**Comment by joasilva** [comment]
So, fixed on next release? :-)

During the Pilot deployment, Patrik had to manually move `/srv/qvain/web/dist` to `/srv/qvain/web`

**Comment by jppiiroinen** [comment]
should be fixed.
